// Arapça çeviriler — anahtar: Türkçe metin (data.json ile birebir)
module.exports = {
SECTIONS: {
 "Kahvaltı":"الفطور","Başlangıçlar":"المقبلات","Ana Yemekler":"الأطباق الرئيسية","Burger & Dürüm":"برجر ولفائف",
 "Pizza & Pide":"بيتزا وبيدة","Tatlılar":"الحلويات","Sıcak İçecekler":"المشروبات الساخنة","Soğuk İçecekler":"المشروبات الباردة","Nargile":"الشيشة"
},
SUBS: {
 "Serpme, sahanda, omlet, gözleme":"فطور مشكّل، بيض بالمقلاة، أومليت، غوزلمه",
 "Çorba, ara sıcaklar, salatalar":"شوربة، مقبلات ساخنة، سلطات",
 "Izgara, güveç, sote, makarna":"مشاوي، طواجن، سوتيه، معكرونة",
 "Hamburger, dürüm, quesadilla":"همبرغر، لفائف، كيساديا",
 "Taş fırından pizza, pide ve tostlar":"بيتزا وبيدة من الفرن الحجري وتوست",
 "Fırın tatlıları, dondurma, tabaklar":"حلويات الفرن، آيس كريم، أطباق",
 "Kahveler, çaylar, sıcak çikolata":"قهوة، شاي، شوكولاتة ساخنة",
 "Kokteyller, smoothie, meyve suları":"كوكتيلات، سموذي، عصائر",
 "Al Fakher & Adalya, özel karışımlar":"الفاخر وأضاليا، خلطات خاصة"
},
GROUPS: {
 "Kahvaltı Tabakları":"أطباق الفطور","Sahanda":"على المقلاة","Omlet Çeşitleri":"أنواع الأومليت","Seçme Kahvaltılıklar":"تشكيلة الفطور",
 "Gözleme Çeşitleri":"غوزلمه","Çorba":"شوربة","Ara Sıcaklar":"مقبلات ساخنة","Salatalar":"سلطات","Izgara Çeşitleri":"من المشواة",
 "Güveç & Fajita":"طواجن وفاهيتا","Tavuk & Et":"دجاج ولحم","Deniz Ürünleri":"مأكولات بحرية","Makarnalar":"معكرونة","Hamburger":"برجر",
 "Dürümler":"لفائف (دوروم)","Quesadilla":"كيساديا","Pizzalar":"بيتزا","Pideler":"بيدة","Tostlar":"توست","Tatlılar":"حلويات",
 "Dondurma & Tabaklar":"آيس كريم وأطباق","Sıcak Kahveler":"قهوة ساخنة","Türk Kahveleri & Klasikler":"قهوة تركية وكلاسيكيات",
 "Sıcak Çikolata":"شوكولاتة ساخنة","Meyveli Çaylar":"شاي بالفواكه","Bitki Çayları":"شاي أعشاب","Soğuk Kahveler":"قهوة مثلجة",
 "Alkolsüz Kokteyller":"كوكتيلات بدون كحول","Taze Sıkılmış Meyve Suları":"عصائر طازجة","Smoothie":"سموذي","Milkshake":"ميلك شيك",
 "Frozen":"فروزن","Şişe & Kutu":"مشروبات معلبة","Klasik Nargileler":"شيشة كلاسيكية","Al Fakher & Adalya Aromaları":"نكهات الفاخر وأضاليا",
 "Özel Nargile Karışımları":"خلطات شيشة خاصة"
},
NOTES: { "Al Fakher & Adalya · Tek fiyat":"الفاخر وأضاليا · سعر موحّد" },
ALG: { G:"غلوتين",M:"حليب",Y:"بيض",B:"سمك",K:"قشريات",S:"صويا",SS:"سمسم",N:"مكسرات",F:"فول سوداني",H:"خردل",C:"كرفس",SO:"كبريتيت",MO:"رخويات",L:"ترمس" },
NAMES: {
 "Kahvaltı Tabağı":"طبق الفطور","Serpme Kahvaltı (2 Kişilik)":"فطور مشكّل (لشخصين)","Sahanda Tereyağlı Göz Yumurta":"بيض مقلي بالزبدة",
 "Kavurmalı Yumurta":"بيض باللحم المحمّر","Sucuklu Yumurta":"بيض بالسجق","Sahanda Sucuk":"سجق مقلي","Sade Menemen":"منمن سادة",
 "Karışık Menemen":"منمن مشكّل","Mıhlama":"مخلمة (جبنة بالذرة والزبدة)","Sade Omlet":"أومليت سادة","Peynirli":"بالجبنة","Karışık":"مشكّل",
 "Peynirli Maydanozlu":"بالجبنة والبقدونس","Kaşar Mantarlı":"بالقشقوان والفطر","Mantarlı":"بالفطر","Sebzeli":"بالخضار",
 "Peynir Tabağı":"طبق أجبان","Bal Kaymak":"عسل وقشطة","Yeşil–Siyah Zeytin Tabağı":"طبق زيتون أخضر وأسود","Domates Salatalık Söğüş":"شرائح طماطم وخيار",
 "Kaşarlı":"بالقشقوان","Beyaz Peynirli":"بالجبنة البيضاء","Patatesli":"بالبطاطس","Kaşarlı Kavurmalı":"قشقوان ولحم محمّر","Kaşarlı Sucuklu":"قشقوان وسجق",
 "Günün Çorbası":"شوربة اليوم","Elma Dilim Patates":"بطاطس ودجز","Parmak Patates":"بطاطس مقلية","Paçanga Böreği":"بوريك باتشانغا",
 "Sigara Böreği":"سيجارة بوريك (لفائف الجبنة)","Tereyağlı Karides":"روبيان بالزبدة","Çıtır Tavuk Sepeti":"سلة دجاج مقرمش","Combo Tabağı":"طبق كومبو",
 "Mevsim Salata":"سلطة الموسم","Çoban Salata":"سلطة الراعي","Peynirli Roka Salatası":"سلطة جرجير بالجبنة","Sıcak Sezar Salata":"سلطة سيزر ساخنة",
 "Sıcak Hellim Salatası":"سلطة حلوم ساخنة","Ton Balıklı Salata":"سلطة تونة","Sıcak Çıtır Tavuk Salatası":"سلطة دجاج مقرمش ساخنة",
 "Sıcak Bombay Salatası":"سلطة بومباي ساخنة","Sıcak Steak Salatası":"سلطة ستيك ساخنة","Sıcak Thai Salatası":"سلطة تايلاندية ساخنة",
 "Barbekü Soslu Antrikot Izgara":"أنتريكوت مشوي بصلصة الباربكيو","Antrikot Izgara":"أنتريكوت مشوي","Izgara Köfte":"كفتة مشوية","Kaşarlı Köfte":"كفتة بالقشقوان",
 "Mantar Soslu Tavuk Izgara":"دجاج مشوي بصلصة الفطر","Dağ Kekikli Tavuk Izgara":"دجاج مشوي بالزعتر الجبلي","Izgara Tavuk Pirzola (But)":"فخذ دجاج مشوي",
 "Kremalı Mantarlı Tavuk Izgara":"دجاج مشوي بالفطر والكريمة","Tavuk Şinitzel":"شنيتزل دجاج","KÖK Special Etli Güveç":"طاجن لحم كوك سبيشال",
 "KÖK Special Tavuklu Güveç":"طاجن دجاج كوك سبيشال","Et Fajita":"فاهيتا لحم","Tavuk Fajita":"فاهيتا دجاج","Köri Soslu Tavuk":"دجاج بصلصة الكاري",
 "Barbekü Soslu Tavuk":"دجاج بصلصة الباربكيو","Soya Soslu Tavuk":"دجاج بصلصة الصويا","Susamlı Tavuk":"دجاج بالسمسم","Meksika Soslu Tavuk":"دجاج بالصلصة المكسيكية",
 "Çökertme Kebabı":"كباب تشوكرتمه","Et Sote":"سوتيه لحم","Tavuk Sote":"سوتيه دجاج","Karides Güveç":"طاجن روبيان","Fettuccine Alfredo":"فيتوتشيني ألفريدو",
 "Spaghetti Bolognese":"سباغيتي بولونيز","Penne Arrabbiata":"بيني أرابياتا","Köri Soslu Tavuklu Penne":"بيني بالدجاج والكاري","Penne Chicken Mushroom":"بيني دجاج وفطر",
 "Pesto Chicken Penne":"بيني دجاج بالبيستو","La Carne Makarna":"معكرونة لا كارني","Hamburger":"همبرغر","Cheeseburger":"تشيز برجر","Meksika Burger":"برجر مكسيكي",
 "Mushroom Burger":"برجر بالفطر","Çıtır Tavuk Burger":"برجر دجاج مقرمش","Barbekü Soslu Burger":"برجر باربكيو","Kök Burger":"كوك برجر","Et Dürüm":"لفافة لحم",
 "Tavuk Dürüm":"لفافة دجاج","Köfte Dürüm":"لفافة كفتة","Etli Quesadilla":"كيساديا لحم","Tavuklu Quesadilla":"كيساديا دجاج","Margarita":"مارغريتا",
 "Vejetaryen Pizza":"بيتزا خضار","Pizza Milano":"بيتزا ميلانو","Pizza Mista":"بيتزا ميستا","Ton Balıklı Pizza":"بيتزا تونة","Napolitan Pizza":"بيتزا نابوليتان",
 "Sucuklu":"بالسجق","Kıymalı":"باللحم المفروم","Kavurmalı":"باللحم المحمّر","Karışık Pide":"بيدة مشكّلة",
 "Cheesecake Çeşitleri":"تشيز كيك (أنواع)","Sufle":"سوفليه","Tiramisu":"تيراميسو","Fırın Sütlaç":"أرز بالحليب مخبوز (سوتلاتش)","Trileçe":"تريليتشه",
 "Kazandibi":"قازان ديبي","Dilim Pastalar":"قطع كيك","Mozaik Pasta":"كيك موزاييك","Brownie":"براوني","Magnolia Çeşitleri":"ماغنوليا (أنواع)","Katmer":"كاتمر",
 "Künefe":"كنافة","1 Top Dondurma":"آيس كريم (كرة واحدة)","4 Top Dondurma":"آيس كريم (4 كرات)","Meyve Tabağı":"طبق فواكه","Çerez Tabağı":"طبق مكسرات",
 "Espresso":"إسبريسو","Double Espresso":"دبل إسبريسو","Macchiato":"ماكياتو","Americano":"أمريكانو","Cafe Latte":"كافيه لاتيه","Cappuccino":"كابتشينو",
 "Mocha":"موكا","Karamel Mocha":"موكا بالكراميل","White Mocha":"وايت موكا","Bardak Çay":"شاي (كوب)","Fincan Çay":"شاي (فنجان)","Türk Kahvesi":"قهوة تركية",
 "Double Türk Kahvesi":"قهوة تركية دبل","Damla Sakızlı Türk Kahvesi":"قهوة تركية بالمستكة","Dibek Kahvesi":"قهوة ديبك","Menengiç Kahvesi":"قهوة البطم (مننغيتش)",
 "Nescafe":"نسكافيه","Filtre Kahve":"قهوة فلتر","Sahlep":"سحلب","Süt":"حليب","Sıcak Çikolata":"شوكولاتة ساخنة","Caramel":"كراميل","Çilek":"فراولة",
 "White":"شوكولاتة بيضاء","Karadut Çayı":"شاي التوت الأسود","Kivi Çayı":"شاي الكيوي","Elma Çayı":"شاي التفاح","Nane Limon":"نعناع وليمون","Yeşil Çay":"شاي أخضر",
 "Ada Çayı":"شاي المريمية","Ihlamur":"زيزفون","Papatya Çayı":"شاي البابونج","Melisa Çayı":"شاي المليسة","Taze Zencefil Çayı":"شاي الزنجبيل الطازج","Kış Çayı":"شاي الشتاء",
 "Ice Latte":"لاتيه مثلج","Ice Mocha":"موكا مثلجة","Ice Caramel Latte":"لاتيه كراميل مثلج","Ice White Mocha":"وايت موكا مثلجة","Ice Americano":"أمريكانو مثلج",
 "Frappe":"فرابيه","Blue Angel":"بلو أنجل","Ultra Violet":"ألترا فايوليت","Green Fairy":"غرين فيري","Karpuz, Pancar, Karadut Üçlüsü":"ثلاثي البطيخ والشمندر والتوت",
 "Kök Mix":"كوك ميكس","Klasik Mojito":"موهيتو كلاسيك","Mojito Frega":"موهيتو فريغا","Strawberry Mojito":"موهيتو فراولة","Apple Mojito":"موهيتو تفاح",
 "Portakal":"برتقال","Nar":"رمان","Limonata":"ليموناضة","Çilekli Naneli":"فراولة ونعناع","KÖK ATO MIX":"كوك أتو ميكس",
 "Çilekli":"فراولة","Muzlu":"موز","Elma":"تفاح","Kivi":"كيوي","Mango":"مانجو","Şeftali":"خوخ","Böğürtlen":"توت العليق","Kavun":"شمام","Karpuz":"بطيخ",
 "Kırmızı Orman Meyveli":"توت أحمر مشكّل","Çikolata":"شوكولاتة","Vanilya":"فانيليا","Karamel":"كراميل","Muz":"موز","Oreo":"أوريو","Karadut":"توت أسود",
 "Coca Cola":"كوكا كولا","Coca Cola Zero":"كوكا كولا زيرو","Sprite":"سبرايت","Fanta":"فانتا","Ice Tea Şeftali":"آيس تي خوخ","Ice Tea Limon":"آيس تي ليمون",
 "Sade Soda":"صودا (مياه غازية)","Limonlu Soda":"صودا بالليمون","Elmalı Soda":"صودا بالتفاح","Çilekli Soda":"صودا بالفراولة","Ayran":"عيران","Naneli Ayran":"عيران بالنعناع",
 "Su":"ماء","Red Bull":"ريد بول","Üzüm":"عنب","Çift Elma":"تفاحتين","Nane":"نعناع","Damla Sakızı":"مستكة","Vanilya Kavun":"فانيليا وشمام",
 "Love 66":"لوف 66","Lady Killer":"ليدي كيلر","Pişmiş Şeftali":"خوخ مشوي","Bakü Night":"باكو نايت","İzmir Romantik":"إزمير رومانتيك","Marilyn Monroe":"مارلين مونرو",
 "Karışık Meyve":"فواكه مشكّلة","Moskova Night":"موسكو نايت","Dejavu":"ديجافو","Plombir":"بلومبير","Moscow Night":"موسكو نايت","Bakü Nights":"باكو نايتس",
 "KÖK Special 1":"كوك سبيشال 1","KÖK Special 2":"كوك سبيشال 2"
},
INGS: {
 "Beyaz peynir, çeçil peyniri, kaşar, salam, yeşil–siyah zeytin, reçel, Nutella, tereyağı, sivri biber, haşlanmış yumurta, domates, salatalık":"جبنة بيضاء، جبنة تشيتشيل، قشقوان، سلامي، زيتون أخضر وأسود، مربى، نوتيلا، زبدة، فلفل أخضر، بيض مسلوق، طماطم، خيار",
 "Peynir tabağı, şarküteri tabağı, reçel çeşitleri, bal, kaymak, tereyağı, Nutella, domates, salatalık, roka söğüş, pişi, sahanda yumurta, patates–sosis":"طبق أجبان، طبق لحوم باردة، تشكيلة مربى، عسل، قشطة، زبدة، نوتيلا، طماطم، خيار، جرجير، بيشي (عجين مقلي)، بيض مقلي، بطاطس ونقانق",
 "Yumurta, tereyağı":"بيض، زبدة","Yumurta, et kavurma, tereyağı":"بيض، لحم محمّر، زبدة","Yumurta, sucuk, tereyağı":"بيض، سجق، زبدة","Sucuk, tereyağı":"سجق، زبدة",
 "Yumurta, domates, sivri biber, tereyağı":"بيض، طماطم، فلفل أخضر، زبدة","Yumurta, domates, sivri biber, sucuk, kaşar peyniri, tereyağı":"بيض، طماطم، فلفل أخضر، سجق، جبنة قشقوان، زبدة",
 "Mısır unu, tereyağı, kolot/dil peyniri":"دقيق ذرة، زبدة، جبنة كولوت","Yumurta, beyaz peynir, tereyağı":"بيض، جبنة بيضاء، زبدة",
 "Yumurta, kaşar peyniri, sucuk, mantar, biber":"بيض، جبنة قشقوان، سجق، فطر، فلفل","Yumurta, beyaz peynir, maydanoz":"بيض، جبنة بيضاء، بقدونس",
 "Yumurta, kaşar peyniri, mantar":"بيض، جبنة قشقوان، فطر","Yumurta, mantar, tereyağı":"بيض، فطر، زبدة","Yumurta, biber, domates, mantar, soğan":"بيض، فلفل، طماطم، فطر، بصل",
 "Beyaz peynir, kaşar peyniri, çeçil peyniri":"جبنة بيضاء، جبنة قشقوان، جبنة تشيتشيل","Bal, kaymak":"عسل، قشطة","Yeşil zeytin, siyah zeytin, zeytinyağı":"زيتون أخضر، زيتون أسود، زيت زيتون",
 "Domates, salatalık, maydanoz":"طماطم، خيار، بقدونس","Gözleme hamuru, kaşar peyniri":"عجينة غوزلمه، جبنة قشقوان","Gözleme hamuru, beyaz peynir, maydanoz":"عجينة غوزلمه، جبنة بيضاء، بقدونس",
 "Gözleme hamuru, patates, baharat":"عجينة غوزلمه، بطاطس، بهارات","Gözleme hamuru, kaşar peyniri, et kavurma":"عجينة غوزلمه، جبنة قشقوان، لحم محمّر",
 "Gözleme hamuru, kaşar peyniri, sucuk":"عجينة غوزلمه، جبنة قشقوان، سجق","Günlük değişir — servis ekibimize danışınız":"تتغير يوميًا — يُرجى سؤال فريق الخدمة",
 "Patates, baharat":"بطاطس، بهارات","Patates, tuz":"بطاطس، ملح","Yufka, pastırma, kaşar peyniri, biber, domates":"عجينة يوفكا، بسطرمة، جبنة قشقوان، فلفل، طماطم",
 "Yufka, beyaz peynir, maydanoz":"عجينة يوفكا، جبنة بيضاء، بقدونس","Karides, tereyağı, sarımsak, limon":"روبيان، زبدة، ثوم، ليمون",
 "Tavuk göğsü, galeta unu, baharat, patates":"صدر دجاج، بقسماط، بهارات، بطاطس","Sosis, nugget, parmak patates, kroket, sigara böreği, soğan halkası":"نقانق، ناغتس، بطاطس مقلية، كروكيت، سيجارة بوريك، حلقات بصل",
 "Marul, domates, salatalık, havuç, mısır, zeytinyağı, limon":"خس، طماطم، خيار، جزر، ذرة، زيت زيتون، ليمون","Domates, salatalık, soğan, biber, maydanoz, zeytinyağı":"طماطم، خيار، بصل، فلفل، بقدونس، زيت زيتون",
 "Roka, beyaz peynir, çeri domates, zeytinyağı, nar ekşisi":"جرجير، جبنة بيضاء، طماطم كرزية، زيت زيتون، دبس رمان","Marul, ızgara tavuk, parmesan, kruton, sezar sos":"خس، دجاج مشوي، بارميزان، خبز محمص، صلصة سيزر",
 "Hellim peyniri, karışık yeşillik, çeri domates, zeytinyağı":"جبنة حلوم، خضار ورقية مشكّلة، طماطم كرزية، زيت زيتون","Ton balığı, marul, mısır, kırmızı soğan, zeytin, limon":"تونة، خس، ذرة، بصل أحمر، زيتون، ليمون",
 "Çıtır tavuk, karışık yeşillik, çeri domates, sos":"دجاج مقرمش، خضار ورقية مشكّلة، طماطم كرزية، صلصة","Köri ve soya soslu tavuk":"دجاج بصلصة الكاري والصويا",
 "Mantar ve soya soslu et":"لحم بالفطر وصلصة الصويا","Soya soslu tavuk":"دجاج بصلصة الصويا","Pilav, patates püresi ve Kök sos eşliğinde":"يُقدَّم مع أرز وبطاطس مهروسة وصلصة كوك",
 "Mantar, biber ve mozzarella peyniri":"فطر، فلفل، جبنة موزاريلا","Mantar, krema, pilav ve patates püresi":"فطر، كريمة، أرز، بطاطس مهروسة",
 "Pilav, patates püresi, tereyağı, limon, karışık yeşillik":"أرز، بطاطس مهروسة، زبدة، ليمون، خضار ورقية مشكّلة",
 "Arpacık soğan, sarımsak, mantar, çeri domates ve pilav eşliğinde":"بصل صغير، ثوم، فطر، طماطم كرزية، يُقدَّم مع الأرز",
 "Bonfile et parçaları, renkli biberler, jülyen soğan, ekşi krema, salsa ve avokado sos":"قطع لحم فيليه، فلفل ملوّن، بصل جوليان، كريمة حامضة، صلصة سالسا وأفوكادو",
 "Bonfile tavuk parçaları, renkli biberler, jülyen soğan, ekşi krema, salsa ve avokado sos":"قطع دجاج فيليه، فلفل ملوّن، بصل جوليان، كريمة حامضة، صلصة سالسا وأفوكادو",
 "Pilav, patates ve yeşillik eşliğinde":"يُقدَّم مع أرز وبطاطس وخضار ورقية","Mantar, biber, soğan ve krema":"فطر، فلفل، بصل، كريمة",
 "Dana bonfile, kibrit patates, yoğurt, tereyağlı domates sos":"فيليه بقري، بطاطس أعواد، لبن زبادي، صلصة طماطم بالزبدة","Pilav eşliğinde":"يُقدَّم مع الأرز",
 "Karides, mantar, kaşar peyniri, tereyağlı domates sos":"روبيان، فطر، جبنة قشقوان، صلصة طماطم بالزبدة","Fettuccine, krema, parmesan, tereyağı":"فيتوتشيني، كريمة، بارميزان، زبدة",
 "Spagetti, dana kıyma, domates sos, parmesan":"سباغيتي، لحم بقري مفروم، صلصة طماطم، بارميزان","Penne, domates sos, sarımsak, acı biber":"بيني، صلصة طماطم، ثوم، فلفل حار",
 "Penne, tavuk, köri, krema":"بيني، دجاج، كاري، كريمة","Penne, tavuk, mantar, krema":"بيني، دجاج، فطر، كريمة","Penne, tavuk, fesleğen pesto, parmesan":"بيني، دجاج، بيستو الريحان، بارميزان",
 "Et, mantar, krema":"لحم، فطر، كريمة","Dana köfte, burger ekmeği, marul, domates, soğan, turşu, sos":"قرص لحم بقري، خبز برجر، خس، طماطم، بصل، مخلل، صلصة",
 "Dana köfte, cheddar peyniri, burger ekmeği, marul, domates, soğan, turşu":"قرص لحم بقري، جبنة شيدر، خبز برجر، خس، طماطم، بصل، مخلل",
 "Acı sos, dilim zeytin, mısır, cheddar peyniri":"صلصة حارة، شرائح زيتون، ذرة، جبنة شيدر","Mantar, krema":"فطر، كريمة",
 "Çıtır tavuk, burger ekmeği, marul, domates, mayonez":"دجاج مقرمش، خبز برجر، خس، طماطم، مايونيز","Dana köfte, barbekü sos, cheddar, burger ekmeği, marul, soğan":"قرص لحم بقري، صلصة باربكيو، شيدر، خبز برجر، خس، بصل",
 "Jülyen et parçaları, karamelize soğan, cheddar peyniri":"قطع لحم جوليان، بصل مكرمل، جبنة شيدر","Dana et, lavaş, domates, soğan, maydanoz, sos":"لحم بقري، خبز لافاش، طماطم، بصل، بقدونس، صلصة",
 "Tavuk, lavaş, domates, soğan, maydanoz, sos":"دجاج، خبز لافاش، طماطم، بصل، بقدونس، صلصة","Köfte, lavaş, domates, soğan, maydanoz, sos":"كفتة، خبز لافاش، طماطم، بصل، بقدونس، صلصة",
 "Tortilla, dana et, cheddar peyniri, renkli biber, soğan":"تورتيلا، لحم بقري، جبنة شيدر، فلفل ملوّن، بصل","Tortilla, tavuk, cheddar peyniri, renkli biber, soğan":"تورتيلا، دجاج، جبنة شيدر، فلفل ملوّن، بصل",
 "Domates sos, mozzarella peyniri":"صلصة طماطم، جبنة موزاريلا","Domates sos, mozzarella, kabak, havuç, mantar, mısır, yeşil biber":"صلصة طماطم، موزاريلا، كوسا، جزر، فطر، ذرة، فلفل أخضر",
 "Domates sos, mozzarella, sucuk, mantar":"صلصة طماطم، موزاريلا، سجق، فطر","Domates sos, mozzarella, sosis, sucuk, salam, renkli biberler, mısır, mantar, dilim siyah zeytin":"صلصة طماطم، موزاريلا، نقانق، سجق، سلامي، فلفل ملوّن، ذرة، فطر، شرائح زيتون أسود",
 "Domates sos, mozzarella, ton balığı, mısır, kırmızı soğan, siyah zeytin":"صلصة طماطم، موزاريلا، تونة، ذرة، بصل أحمر، زيتون أسود","Domates sos, mozzarella, jambon, mantar, renkli biberler":"صلصة طماطم، موزاريلا، جامبون، فطر، فلفل ملوّن",
 "Pide hamuru, kaşar peyniri":"عجينة بيدة، جبنة قشقوان","Pide hamuru, sucuk, kaşar peyniri":"عجينة بيدة، سجق، جبنة قشقوان","Pide hamuru, dana kıyma, biber, domates":"عجينة بيدة، لحم بقري مفروم، فلفل، طماطم",
 "Pide hamuru, et kavurma, kaşar peyniri":"عجينة بيدة، لحم محمّر، جبنة قشقوان","Pide hamuru, kıyma, sucuk, kaşar peyniri, yumurta":"عجينة بيدة، لحم مفروم، سجق، جبنة قشقوان، بيض",
 "Tost ekmeği, kaşar peyniri, tereyağı":"خبز توست، جبنة قشقوان، زبدة","Tost ekmeği, et kavurma, kaşar peyniri":"خبز توست، لحم محمّر، جبنة قشقوان","Tost ekmeği, sucuk, kaşar peyniri":"خبز توست، سجق، جبنة قشقوان",
 "Tost ekmeği, sucuk, salam, kaşar peyniri":"خبز توست، سجق، سلامي، جبنة قشقوان","Domates":"طماطم","Limonlu, frambuazlı, çikolatalı":"بالليمون، بالتوت، بالشوكولاتة",
 "Çikolata, yumurta, un, tereyağı, şeker":"شوكولاتة، بيض، دقيق، زبدة، سكر","Kedidili bisküvi, mascarpone, kahve, kakao, yumurta":"بسكويت ليدي فينغر، ماسكاربوني، قهوة، كاكاو، بيض",
 "Süt, pirinç, şeker, nişasta":"حليب، أرز، سكر، نشا","Kek, süt, krema, karamel sos":"كيك، حليب، كريمة، صلصة كراميل","Süt, şeker, nişasta, pirinç unu":"حليب، سكر، نشا، دقيق أرز",
 "Kek, krema, çikolata veya meyve":"كيك، كريمة، شوكولاتة أو فواكه","Bisküvi, kakao, tereyağı, süt":"بسكويت، كاكاو، زبدة، حليب","Çikolata, un, yumurta, tereyağı, ceviz":"شوكولاتة، دقيق، بيض، زبدة، جوز",
 "Muzlu, çilekli, Oreolu":"بالموز، بالفراولة، بالأوريو","Yufka, kaymak, Antep fıstığı, tereyağı":"عجينة يوفكا، قشطة، فستق حلبي، زبدة",
 "Kadayıf, dil peyniri, tereyağı, şerbet, Antep fıstığı":"كنافة، جبنة، زبدة، شراب سكر، فستق حلبي","Süt, krema, şeker":"حليب، كريمة، سكر","Mevsim meyveleri":"فواكه الموسم",
 "Karışık kuruyemiş ve kuru meyve":"مكسرات وفواكه مجففة مشكّلة","Çekirdek kahve":"قهوة إسبريسو","Çift shot espresso":"جرعتان من الإسبريسو","Espresso, az süt köpüğü":"إسبريسو، القليل من رغوة الحليب",
 "Espresso, sıcak su":"إسبريسو، ماء ساخن","Espresso, süt, süt köpüğü":"إسبريسو، حليب، رغوة حليب","Espresso, süt, bol süt köpüğü":"إسبريسو، حليب، رغوة حليب كثيفة",
 "Espresso, süt, çikolata sosu":"إسبريسو، حليب، صلصة شوكولاتة","Espresso, süt, çikolata sosu, karamel":"إسبريسو، حليب، صلصة شوكولاتة، كراميل","Espresso, süt, beyaz çikolata":"إسبريسو، حليب، شوكولاتة بيضاء",
 "Demlenmiş siyah çay":"شاي أسود مخمّر","Türk kahvesi, su (şeker tercihe göre)":"قهوة تركية، ماء (السكر حسب الرغبة)","Çift porsiyon Türk kahvesi, su":"حصة مضاعفة من القهوة التركية، ماء",
 "Türk kahvesi, damla sakızı, su":"قهوة تركية، مستكة، ماء","Dibekte dövülmüş kahve karışımı":"خلطة قهوة مطحونة بالهاون","Menengiç çekirdeği, süt":"بذور البطم، حليب",
 "Hazır kahve, süt, sıcak su":"قهوة سريعة التحضير، حليب، ماء ساخن","Filtre kahve, su":"قهوة فلتر، ماء","Süt, sahlep, tarçın":"حليب، سحلب، قرفة","Süt":"حليب",
 "Süt, çikolata":"حليب، شوكولاتة","Süt, beyaz çikolata, karamel":"حليب، شوكولاتة بيضاء، كراميل","Süt, beyaz çikolata, çilek":"حليب، شوكولاتة بيضاء، فراولة","Süt, beyaz çikolata":"حليب، شوكولاتة بيضاء",
 "Karadut aroması, sıcak su":"نكهة التوت الأسود، ماء ساخن","Kivi aroması, sıcak su":"نكهة الكيوي، ماء ساخن","Elma aroması, sıcak su":"نكهة التفاح، ماء ساخن",
 "Nane limon aroması, sıcak su":"نكهة النعناع والليمون، ماء ساخن","Yeşil çay yaprağı":"أوراق شاي أخضر","Adaçayı yaprağı":"أوراق المريمية","Ihlamur çiçeği":"زهر الزيزفون",
 "Taze nane, limon":"نعناع طازج، ليمون","Papatya çiçeği":"زهر البابونج","Melisa (oğul otu) yaprağı":"أوراق المليسة","Taze zencefil, limon, bal":"زنجبيل طازج، ليمون، عسل",
 "Karışık kış bitkileri, tarçın, karanfil, limon":"خلطة أعشاب شتوية، قرفة، قرنفل، ليمون","Espresso, soğuk süt, buz":"إسبريسو، حليب بارد، ثلج",
 "Espresso, soğuk süt, çikolata sosu, buz":"إسبريسو، حليب بارد، صلصة شوكولاتة، ثلج","Espresso, soğuk süt, karamel, buz":"إسبريسو، حليب بارد، كراميل، ثلج",
 "Espresso, soğuk süt, beyaz çikolata, buz":"إسبريسو، حليب بارد، شوكولاتة بيضاء، ثلج","Espresso, soğuk su, buz":"إسبريسو، ماء بارد، ثلج","Karamel veya vanilya":"كراميل أو فانيليا",
 "Süt, ananas, vanilya şurubu, coconut püre":"حليب، أناناس، شراب فانيليا، مهروس جوز الهند","Ahududu püresi, limon suyu, soda":"مهروس التوت، عصير ليمون، صودا",
 "Elma suyu, limonata, blue curaçao, mango püre, passion püre":"عصير تفاح، ليموناضة، بلو كوراساو، مهروس مانجو، مهروس باشن فروت",
 "Elma suyu, karpuz, çilek, karadut, pancar, bal":"عصير تفاح، بطيخ، فراولة، توت أسود، شمندر، عسل","Elma suyu, havuç balı, Nutella, muz, çilek":"عصير تفاح، عسل الجزر، نوتيلا، موز، فراولة",
 "Lime, esmer şeker, nane, Sprite":"ليمون أخضر، سكر بني، نعناع، سبرايت","Lime, esmer şeker, nane, Red Bull":"ليمون أخضر، سكر بني، نعناع، ريد بول",
 "Çilek, lime, esmer şeker, nane, Sprite":"فراولة، ليمون أخضر، سكر بني، نعناع، سبرايت","Elma, lime, esmer şeker, nane, Sprite":"تفاح، ليمون أخضر، سكر بني، نعناع، سبرايت",
 "Taze sıkılmış portakal":"برتقال طازج معصور","Taze sıkılmış nar":"رمان طازج معصور","Limon, su, şeker, nane":"ليمون، ماء، سكر، نعناع","Çilek, nane, limon, su":"فراولة، نعناع، ليمون، ماء",
 "Portakal, havuç, elma, nar":"برتقال، جزر، تفاح، رمان","Meyve, yoğurt, buz":"فواكه، لبن زبادي، ثلج","Süt, dondurma, aroma":"حليب، آيس كريم، نكهة","Meyve püresi, buz, şeker şurubu":"مهروس فواكه، ثلج، شراب سكر",
 "Gazlı içecek, kutu":"مشروب غازي، علبة","Şekersiz gazlı içecek, kutu":"مشروب غازي بدون سكر، علبة","Limon aromalı gazlı içecek, kutu":"مشروب غازي بنكهة الليمون، علبة",
 "Portakal aromalı gazlı içecek, kutu":"مشروب غازي بنكهة البرتقال، علبة","Şeftali aromalı soğuk çay":"شاي مثلج بنكهة الخوخ","Limon aromalı soğuk çay":"شاي مثلج بنكهة الليمون",
 "Maden suyu":"مياه معدنية غازية","Limon aromalı maden suyu":"مياه معدنية بنكهة الليمون","Elma aromalı maden suyu":"مياه معدنية بنكهة التفاح","Çilek aromalı maden suyu":"مياه معدنية بنكهة الفراولة",
 "Yoğurt, su, tuz":"لبن زبادي، ماء، ملح","Yoğurt, su, tuz, nane":"لبن زبادي، ماء، ملح، نعناع","Doğal kaynak suyu":"مياه ينابيع طبيعية","Enerji içeceği, kutu":"مشروب طاقة، علبة",
 "Üzüm aromalı nargile tütünü":"معسّل بنكهة العنب","Karpuz aromalı nargile tütünü":"معسّل بنكهة البطيخ","Çilek aromalı nargile tütünü":"معسّل بنكهة الفراولة",
 "Çift elma aromalı nargile tütünü":"معسّل بنكهة التفاحتين","Cappuccino aromalı nargile tütünü":"معسّل بنكهة الكابتشينو","Çikolata aromalı nargile tütünü":"معسّل بنكهة الشوكولاتة",
 "Nane aromalı nargile tütünü":"معسّل بنكهة النعناع","Damla sakızı aromalı nargile tütünü":"معسّل بنكهة المستكة","Vanilya ve kavun aromalı nargile tütünü":"معسّل بنكهة الفانيليا والشمام",
 "Karpuz, passion meyvesi, çiçekler, kavun, çilek, mentol":"بطيخ، باشن فروت، زهور، شمام، فراولة، منثول","Mango, kavun, çilek, nane":"مانجو، شمام، فراولة، نعناع",
 "Fırınlanmış şeftali aroması":"نكهة الخوخ المشوي","Oryantal meyveler, ice":"فواكه شرقية، آيس","Kavun, karpuz, nane":"شمام، بطيخ، نعناع","Gül, yeşil limon, ice":"ورد، ليمون أخضر، آيس",
 "Karışık meyve aroması":"نكهة فواكه مشكّلة","Muz, orman meyveleri, mentol":"موز، فواكه الغابة، منثول","Kavun, karpuz, nane, vanilya":"شمام، بطيخ، نعناع، فانيليا",
 "Buzlu çikolatalı dondurma aroması":"نكهة آيس كريم الشوكولاتة المثلج","Muz, orman meyveleri ve mentol":"موز، فواكه الغابة ومنثول","Oryantal meyveler ve ice":"فواكه شرقية وآيس",
 "Kavun, karpuz, nane ve vanilya":"شمام، بطيخ، نعناع وفانيليا","Kavun, karpuz ve nane":"شمام، بطيخ ونعناع",
 "Karpuz, passion meyvesi, çiçekler, kavun, çilek ve mentol":"بطيخ، باشن فروت، زهور، شمام، فراولة ومنثول","Buzlu çikolatalı dondurma":"آيس كريم شوكولاتة مثلج",
 "Meyveli karışım":"خلطة فواكه","Kahveli karışım":"خلطة قهوة"
}
};
